### ISSUE TITLE
Hackety Hack won't run programs on Linux

### ISSUE THREAD

**Issue by zzak** [ashbb/green_shoes#18]
I can use the editor fine, but when trying to `run` or `load` apps nothing happens.

I'll try to get a error trace if possible, but so far no luck getting any.

**Comment by ashbb** [comment]
Thanks for the information. This was a bug. Now fixed by [this commit](https://github.com/ashbb/green_shoes/commit/74ea936567d6852e998d35b42f9540452f73dd92). Try the latest code.

**Comment by zzak** [comment]
Yay, `run` and `load` work now, good stuff ash!

I'll close this ticket now :)
