### ISSUE TITLE
manual error...

### ISSUE THREAD

**Issue by serialhex** [ashbb/green_shoes#22]
in the green shoes manual you have:

**_snip**_
Now, in your blank window, type in the following:

 Shoes.app do
   background "#DFA"
   para "Welcome to Shoes"
 end

Save to your desktop as welcome.rb.
**_snip**_

and you tell us to run it.  well, disfortunately this code dosnt work out of the box (at least for me anyway) and i needed to add a

require 'green_shoes'

line to my code.  it would be truly spiffy if this wasn't a requirement, but i don't think that it's (realistically) possible without potentially breaking lots of things.  if it _is_ supposed to do that, then it doesn't work on ruby 1.9.2 p180 with the latest green_shoes (i just installed it) running on opensuse 11.4 (at least that's what i'm working with).

i haven't played with it much more than that, but i'm glad to see the fully ruby-based version of shoes is doing well!! :D  keep up the good work!!
hex

**Comment by ashbb** [comment]
Hi Hex,

Oh, you are right! Good suggestion, thanks. :)

I'm going to add `require 'green_shoes'` into the sample snippet on built-in manual.

So, can I ask you a favor?  
I don't have an English notepad. Could you take this snapshot with `require 'green_shoes'` ?

https://github.com/ashbb/green_shoes/blob/master/static/man-editor-notepad.png

I'd also like to replace the above snapshot.

ashbb

**Comment by serialhex** [comment]
ashbb,

it's your lucky day!  i'm at work and i'm on windows 7, so i can provide such a snapshot.  (if you want one without the spiffy win7 gui i can provide that too)  heres the link:

https://sites.google.com/site/serialhex/notepad.png?attredirects=0

if that link dosnt work, let me know and i'll find your email address and send it direct.

take care!
hex

**Comment by ashbb** [comment]
Cool!  
I'll update with your snapshot asap. Thanks!

**Comment by serialhex** [comment]
...i dont think this needs to be open anymore... closing!

**Comment by ashbb** [comment]
Updated to [0.199.0](https://github.com/ashbb/green_shoes/commit/7f8d55d95b526839ee39c59002f27dd86daa9219). Thanks!
