### ISSUE TITLE
Theory of Signals and Callbacks

### ISSUE THREAD

**Issue by zzak** [ashbb/green_shoes#3]
I think we have talked about handling signals in shoes, and I found this article on the ruby-gtk2 website: http://ruby-gnome2.sourceforge.net/tut/3.2.htm

**Comment by ashbb** [comment]
Thanks! I've read that article. And also found **Gtk.timeout_add** method . Then tried to write [this](http://github.com/ashbb/green_shoes/blob/master/shoes/main.rb#L44). ;-)
