### ISSUE TITLE
README and pull request

### ISSUE THREAD

**Issue by glurp** [ashbb/green_shoes#37]
Hello,

Last week I work very hard to make a pull request.... not git professional 

Is it possible to add this kind of text to your README :
# 

== Note on Patches/Pull Requests
- Fork the project.
- Make your feature addition or bug fix ( addition to lib/plugins or lib/ext, buf fix direct in source) 
- Add a  sampleXX.rb in sample dir - if addition) 
- Commit, do not mess with rakefile, version, or history. (if you want to have your own version, that is fine but bump version in a commit by itself in another branch so I can ignore when I pull) 
- Send me a pull request. 
# 

(this is extraction from httparty README) 

NOTA: memory leaks seem disparate from long-time run of sample54.rb : memory stabilize at 40MB (!) 

by

**Comment by ashbb** [comment]
> Is it possible to add this kind of text to your README 

Yes. Please send me the pull request. I'll merge.

> NOTA: memory leaks seem disparate from long-time run of sample54.rb : memory stabilize at 40MB (!) 

Oh, really? Umm,... why 40MB...

**Comment by krainboltgreene** [comment]
Working on the readme bit now.
