### ISSUE TITLE
Event from alert button are (sometime) fired to the element behind alert() window!

### ISSUE THREAD

**Issue by glurp** [ashbb/green_shoes#48]
Hello,
I do not want boring you, but,
here is a old bug that can appeared furtively.

``` ruby
require 'green_shoes'

Shoes.app do
  flow { title "aaa" }.click { alert("aaa: move me, with the 'valid' button on the 'ccc' field, and click !") }
  flow { title "bbb" }.click { alert("bbb: move me, with the 'valid' button on the 'ccc' field, and click !") }
  flow { title "ccc" }.click { alert("You have clicked on 'ccc'") }
end
```

by

**Comment by glurp** [comment]
and same issue under Linux, same code.
the alert of 'ccc' do not interfer with other title (aaa and bbb).

**Comment by ashbb** [comment]
Hi Regis,

Thank you for finding a bug! I confirmed and I didn't notice this strange behavior.

But coincidentally, [GutenYe](https://github.com/GutenYe) sent me [pull requests](https://github.com/ashbb/green_shoes/commits/master) a few days ago.
His commits seem to solve this issue, too!

Try out to use alert() with `:block => false` option.

The default value of :block option is true for now to keep current behavior. 
But it may be better to reconsider again.

ashbb

ps. I notice that this issue will be happen for confirm(), ask(), etc. Need to more study for them.

**Comment by glurp** [comment]
Hello Ashbb

Ok for alert() , but what for ask_blabla() ? :

require 'green_shoes'

``` ruby
Shoes.app do
  flow { title "aaa" }.click { ask_open_file() }
  flow { title "bbb" }.click { alert("bbb: move me, with the 'valid' button
on the 'ccc' field, and click !") }
  flow { title "ccc" }.click { alert("You have clicked on 'ccc'") }
end
```

It is perhaps a gtk issue?

by

2011/8/25 ashbb <
reply@reply.github.com>

> Hi Regis,
> 
> Thank you for finding a bug! I confirmed and I didn't notice this strange
> behavior.
> 
> But coincidentally, [GutenYe](https://github.com/GutenYe) sent me [pull
> requests](https://github.com/ashbb/green_shoes/commits/master) a few days
> ago.
> His commits seem to solve this issue, too!
> 
> Try out to use alert with `:block => false` option.
> 
> The default value of :block option is true for now to keep current
> behavior.
> But it may be better to reconsider again.
> 
> ashbb
> 
> ps. I notice that this issue will be happen for confirm(), ask(), etc. Need
> to more study for them.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ashbb/green_shoes/issues/48#issuecomment-1898823

## 

---

 __   ___  __   .  __
|**) |**  / _`  | /__`
|  \ |___ __> L| .__/

http://regisaubarede.posterous.com/

---

**Comment by ashbb** [comment]
Yeah, I intended that 'confirm(), ask(), etc.' included ask_blabla(). :-P

> It is perhaps a gtk issue?

I'm not sure. But need to study how to use `dialog.run`.

**Comment by ashbb** [comment]
Hi raubarede,

Sorry, it's my fault. Ruby/GTK2 is innocent. Now fixed. Look at [the commit](https://github.com/ashbb/green_shoes/commit/051f6bce7b91158a3dafdfc5fe8fb29a59d62c56).

ashbb

**Comment by glurp** [comment]
super, 
I will diffuse my p2p tools thes we...
