### ISSUE TITLE
scoll slot

### ISSUE THREAD

**Issue by glurp** [ashbb/green_shoes#53]
Hello Ashbb,

in this code , show only the button if :scroll==true
but scroll bar is there if no options !

```
require 'green_shoes' 
 Shoes.app do
    stack :scroll=> true do
        100.times { para "do scroll=false for scroll..." }
        button "a button"
    end
end
```

with  green_shoes-1.0.282.gem

by,
Regis

**Comment by ashbb** [comment]
Hi Regis,

hahaha. Yeah, scrolled slot is just a trial on Green Shoes.
So, there are many restrictions. Look at manual: http://ashbb.github.com/green_shoes/Styles.html#:scroll

And try out the following:

<pre>
require 'green_shoes'
Shoes.app do
  stack :scroll=> true do
    100.times { para "do scroll=false for scroll..." }
    button "a button"
    flush
  end
end
</pre>

Yes, you need to write flush explicitly. ;-)

ashbb
