### ISSUE TITLE
No gemspec: can't include gem version from git

### ISSUE THREAD

**Issue by translunar** [ashbb/green_shoes#54]
I know we talked about the gemspec before, and I realize you can generate one after pulling Green Shoes, but here's a reason to include one in the repo. Maybe you know a better way to go about this.

I have a Gemfile (for bundler) which is setup to pull the most recent version of Green Shoes from git:

```
gem "green_shoes", :git => "git://github.com/ashbb/green_shoes"
```

But without a gemspec, it gives:

```
Could not find gem 'green_shoes (>= 0)' in git://github.com/ashbb/green_shoes (at master).
Source does not contain any versions of 'green_shoes (>= 0)'
```

The only way around this is for me to fork green shoes and give it my own repo as the git source.

John

**Comment by ashbb** [comment]
OHHHH. Good to know. I have thought that I have to upload a gemfile itself to github. xx-P
Okay, I'll build a gemspec file and upload to github repo.

Thanks!
