### ISSUE TITLE
download() method example error

### ISSUE THREAD

**Issue by ujk** [ashbb/green_shoes#65]
On example at http://ashbb.github.com/green_shoes/App.html#download 

```
  @status.text = "Headers: #{goog.meta}" 
```

it can't change the text of para element because of goog.meta returns Hash object. If I change it like:

```
  @status.text = "Date: #{goog.meta["date"]}"
```

it runs well. I'm using windows7 and Ruby 1.9.2p180

**Comment by ashbb** [comment]
Hi ujk,

Thank you for letting me know. Now, fixed. :)
