### ISSUE TITLE
ask_open_file dialog: Can it accept default folder name?

### ISSUE THREAD

**Issue by meruby** [ashbb/green_shoes#66]
Is there any way to pass default folder name which ask_open_file dialog will use to show files in that folder instead of default folder.

**Comment by ashbb** [comment]
Hi meruby,

Thank you for the very good suggestion!
I've implemented your request just now. So, try out the following with the latest gem (green_shoes 1.1.363).

``` ruby
Shoes.app do
  ask_open_file "c:/tmp"
end
```

See [the commit](https://github.com/ashbb/green_shoes/commit/c45cc27221586919555909469c501abf1dcbc583). Hope this helps. ;-)

**Comment by meruby** [comment]
Hi ashbb,
  Thanks for your quick modification. It work perfectly. 

  If you don't mind I have another suggestion: In dropdown, can you allow user to type text, if what they want is not there in the selection? This modified dropdown needs to be something different than default dropdown since display value might be there in the dropdown list. My reason for this is: there are times when we learn what value user want from what they type. For ex. tagging: we want user to select from previous tagging list, but we want to allow them to type new one too.

I understand that you might not want to add this, because it is too cumbersome, or it does not go well with shoes philosophy of simplicity.

Once again thanks for quickly adding default folder option to ask_open_file.

Samir

**Comment by ashbb** [comment]
Thanks for the new suggestion. It's useful!
So, I've implemented as Green Shoes 1.1.364. Try it out. :)

See [the commit](https://github.com/ashbb/green_shoes/commit/bb051a629c2e7879ff4635bb3b12e8c462686870).

**Comment by meruby** [comment]
Hi ashbb,
  It work as expected. Thanks again. I realized later that I should have open another issue for this one. 
Samir
